// <auto-generated />
using System;
using CRUDAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220210032519_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("CRUDAPI.Data.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("birth_date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("login")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("mother_name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birth_date = new DateTime(2003, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5908),
                            email = "LeonorSantosFernandes@teleworm.us",
                            login = "Theired1995",
                            mother_name = "Dias",
                            name = "Leonor",
                            password = "Eipai7Da6ut",
                            status = true,
                            telephone = "(11) 8703-2327",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5909)
                        },
                        new
                        {
                            id = 2,
                            birth_date = new DateTime(2001, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5916),
                            email = "MelissaCavalcantiPereira@armyspy.com",
                            login = "Whords",
                            mother_name = "Cardoso",
                            name = "Melissa",
                            password = "AhFeesha8",
                            status = true,
                            telephone = "(11) 8591-3354",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5917)
                        },
                        new
                        {
                            id = 3,
                            birth_date = new DateTime(1999, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5922),
                            email = "BrendaAlmeidaCardoso@jourrapide.com",
                            login = "Sirsomand",
                            mother_name = "Cunha",
                            name = "Brenda",
                            password = "ohCaoha1Oo",
                            status = true,
                            telephone = "(12) 3650-4890",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5922)
                        },
                        new
                        {
                            id = 4,
                            birth_date = new DateTime(1998, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5927),
                            email = "LuizPereiraAlves@armyspy.com",
                            login = "Youria",
                            mother_name = "Carvalho",
                            name = "Luiz",
                            password = "wee2mo8Ohj",
                            status = true,
                            telephone = "(16) 4636-2302",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5928)
                        },
                        new
                        {
                            id = 5,
                            birth_date = new DateTime(1996, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5934),
                            email = "JulianFerreiraOliveira@dayrep.com",
                            login = "Hingere",
                            mother_name = "Rodrigues",
                            name = "Julian",
                            password = "eWae2oos",
                            status = true,
                            telephone = "(31) 5173-6191",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5934)
                        },
                        new
                        {
                            id = 6,
                            birth_date = new DateTime(1994, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5939),
                            email = "ThaisDiasPinto@teleworm.us",
                            login = "Adlial",
                            mother_name = "Oliveira",
                            name = "Thaís",
                            password = "Bahxe1ku8koi",
                            status = true,
                            telephone = "(67) 6101-5582",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            id = 7,
                            birth_date = new DateTime(1992, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5945),
                            email = "DouglasOliveiraRocha@jourrapide.com",
                            login = "Marknow",
                            mother_name = "Azevedo",
                            name = "Douglas",
                            password = "Aiv6Iquohcae",
                            status = true,
                            telephone = "(61) 3118-6336",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5945)
                        },
                        new
                        {
                            id = 8,
                            birth_date = new DateTime(1990, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5951),
                            email = "RafaelSouzaAzevedo@teleworm.us",
                            login = "Curtand",
                            mother_name = "Ferreira",
                            name = "Rafael",
                            password = "auJich6yutie",
                            status = true,
                            telephone = "(11) 2485-5791",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5951)
                        },
                        new
                        {
                            id = 9,
                            birth_date = new DateTime(1988, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5956),
                            email = "EnzoSouzaOliveira@dayrep.com",
                            login = "Kelin2001",
                            mother_name = "Oliveira",
                            name = "Enzo",
                            password = "EaVohth5",
                            status = true,
                            telephone = "(12) 6637-3409",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5957)
                        },
                        new
                        {
                            id = 10,
                            birth_date = new DateTime(1986, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5962),
                            email = "KaueCardosoSouza@dayrep.com",
                            login = "Artagglacte",
                            mother_name = "Almeida",
                            name = "Kauê",
                            password = "Reew7eisu8",
                            status = true,
                            telephone = "11111111111",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5962)
                        },
                        new
                        {
                            id = 11,
                            birth_date = new DateTime(1984, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5968),
                            email = "GiovannaLimaGoncalves@dayrep.com",
                            login = "Magur2002",
                            mother_name = "Cavalcanti",
                            name = "Giovanna",
                            password = "ieW2eZii",
                            status = true,
                            telephone = "(61) 9269-9311",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5968)
                        },
                        new
                        {
                            id = 12,
                            birth_date = new DateTime(1982, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5973),
                            email = "CarolinaGoncalvesLima@dayrep.com",
                            login = "Hadeard",
                            mother_name = "Costa",
                            name = "Carolina",
                            password = "Dewea3ooxai",
                            status = true,
                            telephone = "(67) 7410-5849",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5974)
                        },
                        new
                        {
                            id = 13,
                            birth_date = new DateTime(1980, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5979),
                            email = "RafaelaCarvalhoGoncalves@dayrep.com",
                            login = "Hicarrim",
                            mother_name = "Fernandes",
                            name = "Rafaela",
                            password = "aehieQu5sh",
                            status = true,
                            telephone = "(43) 3801-6229",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5979)
                        },
                        new
                        {
                            id = 14,
                            birth_date = new DateTime(1978, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5984),
                            email = "DaviMeloPinto@jourrapide.com",
                            login = "Plicaut",
                            mother_name = "Lima",
                            name = "Davi",
                            password = "yaX8Geen8ae",
                            status = true,
                            telephone = "(28) 5722-9255",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5985)
                        },
                        new
                        {
                            id = 15,
                            birth_date = new DateTime(1976, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5990),
                            email = "LuizFerreiraAlmeida@rhyta.com",
                            login = "Fourpried2001",
                            mother_name = "Santos",
                            name = "Luiz",
                            password = "Lae8je7zi",
                            status = true,
                            telephone = "(46) 5457-2796",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            id = 16,
                            birth_date = new DateTime(1974, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5995),
                            email = "DanielSantosRodrigues@rhyta.com",
                            login = "Magere01",
                            mother_name = "Almeida",
                            name = "Daniel",
                            password = "ahki3rouP",
                            status = true,
                            telephone = "(48) 8394-9490",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(5996)
                        },
                        new
                        {
                            id = 17,
                            birth_date = new DateTime(1972, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6001),
                            email = "RebecaBarbosaRodrigues@dayrep.com",
                            login = "Therintord",
                            mother_name = "Melo",
                            name = "Rebeca",
                            password = "Iema8air9Ei",
                            status = true,
                            telephone = "(18) 8674-7184",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6001)
                        },
                        new
                        {
                            id = 18,
                            birth_date = new DateTime(1970, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6006),
                            email = "EmilySousaFernandes@jourrapide.com",
                            login = "Awass2000",
                            mother_name = "Pereira",
                            name = "Emily",
                            password = "aV4zooShoo",
                            status = true,
                            telephone = "(16) 7499-9561",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6007)
                        },
                        new
                        {
                            id = 19,
                            birth_date = new DateTime(1968, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6011),
                            email = "AntonioPereiraOliveira@dayrep.com",
                            login = "Drefoldn",
                            mother_name = "Barros",
                            name = "Antônio",
                            password = "hee7Aibuo",
                            status = true,
                            telephone = "(82) 8720-7834",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6012)
                        },
                        new
                        {
                            id = 20,
                            birth_date = new DateTime(1966, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            created_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6017),
                            email = "DouglasLimaCastro@teleworm.us",
                            login = "Opith1999",
                            mother_name = "Cunha",
                            name = "Douglas",
                            password = "aiyaegh7Oh",
                            status = true,
                            telephone = "(16) 7499-9561",
                            updated_at = new DateTime(2022, 2, 10, 3, 25, 19, 824, DateTimeKind.Utc).AddTicks(6018)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
